name: Storybook

on:
  push:
    branches:
      - master
      - develop
      - dev/storybook8 # for testing
  pull_request_target:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_OPTIONS: "--max_old_space_size=7168"

    steps:
    - uses: actions/checkout@v4.1.1
      if: github.event_name != 'pull_request_target'
      with:
        fetch-depth: 0
        submodules: true
    - uses: actions/checkout@v4.1.1
      if: github.event_name == 'pull_request_target'
      with:
        fetch-depth: 0
        submodules: true
        ref: "refs/pull/${{ github.event.number }}/merge"
    - name: Checkout actual HEAD
      if: github.event_name == 'pull_request_target'
      id: rev
      run: |
        echo "base=$(git rev-list --parents -n1 HEAD | cut -d" " -f2)" >> $GITHUB_OUTPUT
        git checkout $(git rev-list --parents -n1 HEAD | cut -d" " -f3)
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4.0.3
      with:
        node-version-file: '.node-version'
        cache: 'pnpm'
    - run: corepack enable
    - run: pnpm i --frozen-lockfile
    - name: Check pnpm-lock.yaml
      run: git diff --exit-code pnpm-lock.yaml
    - name: Build misskey-js
      run: pnpm --filter misskey-js build
    - name: Build storybook
      run: pnpm --filter frontend build-storybook
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: storybook
        path: packages/frontend/storybook-static
